CREATE TABLE IF NOT EXISTS login_aliases (
  username TEXT PRIMARY KEY,
  user_email TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
);
