export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS users (
    email TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    plan TEXT NOT NULL DEFAULT 'free' CHECK (plan IN ('free', 'plus')),
    plan_tier TEXT NOT NULL DEFAULT 'free',
    referral_code TEXT,
    referred_by TEXT,
    bonus_pages INTEGER NOT NULL DEFAULT 0,
    referral_rewarded INTEGER NOT NULL DEFAULT 0,
    billing_customer_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    owner_email TEXT NOT NULL,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    template_id TEXT NOT NULL,
    config_json TEXT NOT NULL,
    access_password_hash TEXT,
    published INTEGER NOT NULL DEFAULT 0,
    views INTEGER NOT NULL DEFAULT 0,
    clicks INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS projects_owner_idx ON projects(owner_email)`,
  `CREATE INDEX IF NOT EXISTS projects_slug_idx ON projects(slug)`,
  `CREATE TABLE IF NOT EXISTS project_backgrounds (
    project_id TEXT PRIMARY KEY,
    mime TEXT NOT NULL,
    data BLOB NOT NULL,
    object_key TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS project_emoji_images (
    project_id TEXT PRIMARY KEY,
    mime TEXT NOT NULL,
    data BLOB NOT NULL,
    object_key TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS support_requests (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    topic TEXT NOT NULL,
    message TEXT NOT NULL,
    page_url TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS support_requests_created_idx ON support_requests(created_at)`,
  `CREATE TABLE IF NOT EXISTS rate_limits (
    key TEXT PRIMARY KEY,
    count INTEGER NOT NULL DEFAULT 0,
    reset_at INTEGER NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS rate_limits_reset_idx ON rate_limits(reset_at)`,
  `CREATE TABLE IF NOT EXISTS billing_events (
    event_id TEXT PRIMARY KEY,
    event_type TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    payload_json TEXT,
    provider_event_at TEXT,
    sequence INTEGER,
    status TEXT NOT NULL DEFAULT 'processed' CHECK (status IN ('received', 'processing', 'processed', 'ignored', 'failed')),
    processed_at TEXT,
    received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS billing_events_received_idx ON billing_events(received_at)`,
  `CREATE TABLE IF NOT EXISTS billing_customers (
    user_email TEXT PRIMARY KEY,
    provider TEXT NOT NULL DEFAULT 'hosted',
    provider_customer_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    provider TEXT NOT NULL DEFAULT 'hosted',
    provider_order_id TEXT,
    plan TEXT NOT NULL,
    price_id TEXT,
    amount_minor INTEGER NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'ILS',
    status TEXT NOT NULL CHECK (status IN ('pending', 'paid', 'refunded', 'chargeback', 'failed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TEXT,
    provider_event_at TEXT
  )`,
  `CREATE INDEX IF NOT EXISTS orders_user_idx ON orders(user_email, created_at)`,
  `CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    provider_subscription_id TEXT,
    plan TEXT NOT NULL,
    price_id TEXT,
    status TEXT NOT NULL CHECK (status IN ('active', 'past_due', 'cancel_scheduled', 'cancelled', 'expired')),
    current_period_end TEXT,
    cancel_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS subscriptions_user_idx ON subscriptions(user_email, status)`,
  `CREATE TABLE IF NOT EXISTS marketing_events (
    id TEXT PRIMARY KEY,
    event_name TEXT NOT NULL,
    user_email TEXT,
    campaign_source TEXT,
    campaign_medium TEXT,
    campaign_name TEXT,
    campaign_content TEXT,
    campaign_term TEXT,
    template_id TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE SET NULL
  )`,
  `CREATE INDEX IF NOT EXISTS marketing_events_name_created_idx ON marketing_events(event_name, created_at)`,
  `CREATE INDEX IF NOT EXISTS marketing_events_campaign_idx ON marketing_events(campaign_source, campaign_name, created_at)`,
  `CREATE INDEX IF NOT EXISTS marketing_events_user_idx ON marketing_events(user_email, created_at)`,
  `CREATE TABLE IF NOT EXISTS marketing_leads (
    email TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    use_case TEXT NOT NULL,
    campaign_source TEXT,
    campaign_medium TEXT,
    campaign_name TEXT,
    campaign_content TEXT,
    campaign_term TEXT,
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'converted', 'closed')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS marketing_leads_status_created_idx ON marketing_leads(status, created_at)`,
  `CREATE TABLE IF NOT EXISTS auth_credentials (
    email TEXT PRIMARY KEY,
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    password_iterations INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    last_seen_at INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS sessions_user_idx ON sessions(user_email)`,
  `CREATE INDEX IF NOT EXISTS sessions_expires_idx ON sessions(expires_at)`,
  `CREATE TABLE IF NOT EXISTS login_aliases (
    username TEXT PRIMARY KEY,
    user_email TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS email_verifications (
    user_email TEXT PRIMARY KEY,
    verified_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS auth_tokens (
    token_hash TEXT PRIMARY KEY,
    user_email TEXT NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN ('verify_email', 'reset_password', 'change_password', 'delete_account')),
    expires_at INTEGER NOT NULL,
    used_at INTEGER,
    payload TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS auth_tokens_user_purpose_idx ON auth_tokens(user_email, purpose)`,
  `CREATE INDEX IF NOT EXISTS auth_tokens_expires_idx ON auth_tokens(expires_at)`,
  `CREATE TABLE IF NOT EXISTS user_controls (
    email TEXT PRIMARY KEY,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    note TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT NOT NULL,
    FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS user_controls_status_idx ON user_controls(status)`,
  `CREATE TABLE IF NOT EXISTS admin_audit_log (
    id TEXT PRIMARY KEY,
    admin_email TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    details_json TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS admin_audit_created_idx ON admin_audit_log(created_at)`,
  `CREATE TABLE IF NOT EXISTS rsvp_responses (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('yes', 'maybe', 'no')),
    guest_count INTEGER NOT NULL DEFAULT 1,
    plus_ones_json TEXT,
    song TEXT,
    answers_json TEXT,
    name TEXT NOT NULL,
    contact_hash TEXT,
    response_token_hash TEXT NOT NULL UNIQUE,
    ip_hash TEXT,
    consent_at TEXT NOT NULL,
    expires_at INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS rsvp_responses_project_idx ON rsvp_responses(project_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS rsvp_responses_token_idx ON rsvp_responses(response_token_hash)`,
  `CREATE INDEX IF NOT EXISTS rsvp_responses_contact_idx ON rsvp_responses(project_id, contact_hash)`,
  `CREATE INDEX IF NOT EXISTS rsvp_responses_expires_idx ON rsvp_responses(expires_at)`,
];
